# Generated by Django 6.0.6 on 2026-06-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_updated_at_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
