# Generated by Django 6.0.6 on 2026-06-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_project_is_catchall'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
