# Generated by Django 6.0.6 on 2026-07-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_recurringtodo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringtodo',
            options={'ordering': ['day_of_week', 'id']},
        ),
        migrations.AddField(
            model_name='recurringtodo',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6),
        ),
    ]
