# Generated by Django 6.0.6 on 2026-07-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_alter_recurringtodo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtodo',
            name='days_until_due',
        ),
    ]
