# Generated by Django 6.0.6 on 2026-07-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0012_todo_source_todo_unique_recurring_todo_per_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtodo',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.TextField(),
        ),
    ]
